[phases.setup]
nixPkgs = ["chromium", "nss", "freetype", "harfbuzz", "ca-certificates", "glib", "nssTools"]

[phases.install]
cmds = ["npm install"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
